export const questionsByCategory = {
    "Personal / Psychology / Aptitude": [
      "How do you handle stress and pressure?",
      "Describe your problem-solving approach",
      "How do you manage time effectively?",
      "What are your leadership qualities?",
      "How do you handle conflicts?",
      "Describe your communication style",
      "What motivates you?",
      "How do you adapt to change?",
      "Describe your ideal work environment",
      "What are your career goals?",
    ],
    Technical: {
      "Java Full Stack": [
        "How do you rate yourself in Core Java?",
        "Rate your expertise in Spring Boot",
        "How comfortable are you with RESTful APIs?",
        "Rate your understanding of JPA/Hibernate",
        "How well do you know Maven/Gradle?",
        "Rate your experience with Microservices",
        "How proficient are you in SQL?",
        "Rate your frontend skills (HTML/CSS/JS)",
        "How well do you understand Design Patterns?",
        "Rate your testing knowledge (JUnit/Mockito)",
      ],
      "MERN Stack": [
        "How do you rate yourself in MongoDB?",
        "Rate your expertise in Express.js",
        "How comfortable are you with React.js?",
        "Rate your Node.js knowledge",
        "How well do you know REST APIs?",
        "Rate your experience with State Management",
        "How proficient are you in JavaScript/TypeScript?",
        "Rate your understanding of NoSQL concepts",
        "How well do you know Git?",
        "Rate your testing knowledge (Jest/RTL)",
      ],
      DevOps: [
        "How do you rate yourself in Docker?",
        "Rate your expertise in Kubernetes",
        "How comfortable are you with CI/CD?",
        "Rate your AWS/Cloud knowledge",
        "How well do you know Linux?",
        "Rate your experience with Jenkins",
        "How proficient are you in Shell Scripting?",
        "Rate your understanding of Monitoring tools",
        "How well do you know Version Control?",
        "Rate your Infrastructure as Code knowledge",
      ],
    },
    "Professional / Responsibility": [
      "How do you ensure code quality?",
      "Describe your experience with Agile",
      "How do you handle deadlines?",
      "Experience with code reviews?",
      "How do you document your work?",
      "Approach to mentoring juniors?",
      "How do you stay updated with technology?",
      "Experience with client communication?",
      "How do you handle production issues?",
      "Describe your project management skills",
    ],
  }
  
  